# Generated by Django 4.2.2 on 2023-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoConts', '0003_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
