# Generated by Django 4.2.2 on 2023-10-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightIndexLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.CharField(help_text='a diapozone of weight indexes in numbers', max_length=50)),
                ('category_name', models.CharField(help_text='name of a weight index diapozone', max_length=50)),
                ('description', models.TextField(help_text='a short description for a diapozone', max_length=1000)),
            ],
        ),
    ]
